#!/usr/bin/env bash
#
# One-time (idempotent) provisioning for a fresh Ubuntu 24.04 VPS.
# Run as root ON THE SERVER:
#
#   scp -r deploy root@YOUR_VPS:/root/ipcrawl-deploy
#   ssh root@YOUR_VPS 'bash /root/ipcrawl-deploy/setup-vps.sh'
#
# Safe to re-run: every step checks before acting. It does NOT deploy the app
# (use deploy.sh from your laptop for that) and does NOT migrate data
# (use migrate-data.sh). After this finishes, drop /srv/ipcrawl/env in place
# (from deploy/env.example) and your Cloudflare origin cert, then deploy.
set -euo pipefail

APP_USER=ipcrawl
APP_ROOT=/srv/ipcrawl
NODE_MAJOR=22
DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

if [[ $EUID -ne 0 ]]; then
  echo "Must run as root." >&2
  exit 1
fi

# --- Packages ---------------------------------------------------------------
log "Installing base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y ca-certificates curl gnupg ufw nginx sqlite3 rsync

log "Installing rclone (for the R2 -> SSD data sync)"
if ! command -v rclone >/dev/null 2>&1; then
  curl -fsSL https://rclone.org/install.sh | bash
else
  echo "rclone already installed: $(rclone version | head -n1)"
fi

# --- Node 22 (NodeSource) ---------------------------------------------------
log "Installing Node ${NODE_MAJOR} (node:sqlite needs >= 22.5)"
NEED_NODE=1
if command -v node >/dev/null 2>&1; then
  CURRENT_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
  if [[ "$CURRENT_MAJOR" -ge "$NODE_MAJOR" ]]; then
    echo "Node $(node -v) already present."
    NEED_NODE=0
  fi
fi
if [[ "$NEED_NODE" -eq 1 ]]; then
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
  apt-get install -y nodejs
fi
node -v

# --- App user + directories -------------------------------------------------
log "Creating ${APP_USER} system user and ${APP_ROOT} tree"
if ! id "$APP_USER" >/dev/null 2>&1; then
  useradd --system --home-dir "$APP_ROOT" --shell /usr/sbin/nologin "$APP_USER"
fi
mkdir -p "$APP_ROOT/app" "$APP_ROOT/data" "$APP_ROOT/backups"
# App code is delivered by deploy.sh over rsync as this user; data is written
# by the running service.
chown -R "$APP_USER:$APP_USER" "$APP_ROOT"
# Screenshots + sqlite live here; keep them private.
chmod 750 "$APP_ROOT/data"

# --- Cloudflare real-IP + firewall ------------------------------------------
log "Fetching Cloudflare IP ranges (real_ip + firewall allowlist)"
CF_V4="$(curl -fsSL https://www.cloudflare.com/ips-v4)"
CF_V6="$(curl -fsSL https://www.cloudflare.com/ips-v6)"
if [[ -z "$CF_V4" ]]; then
  echo "Failed to fetch Cloudflare IPv4 ranges; aborting so we don't lock nginx to nothing." >&2
  exit 1
fi

REALIP_CONF=/etc/nginx/cloudflare-realip.conf
log "Writing ${REALIP_CONF}"
{
  echo "# Auto-generated by setup-vps.sh from cloudflare.com/ips-*. Do not edit."
  echo "# Re-run setup-vps.sh to refresh (Cloudflare updates these rarely)."
  while IFS= read -r cidr; do [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"; done <<< "$CF_V4"
  while IFS= read -r cidr; do [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"; done <<< "$CF_V6"
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$REALIP_CONF"

log "Configuring ufw (SSH open; HTTP/HTTPS only from Cloudflare)"
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp comment 'SSH'
while IFS= read -r cidr; do
  [[ -n "$cidr" ]] && ufw allow from "$cidr" to any port 80 proto tcp comment 'Cloudflare HTTP'
  [[ -n "$cidr" ]] && ufw allow from "$cidr" to any port 443 proto tcp comment 'Cloudflare HTTPS'
done <<< "$CF_V4"
while IFS= read -r cidr; do
  [[ -n "$cidr" ]] && ufw allow from "$cidr" to any port 80 proto tcp comment 'Cloudflare HTTP v6'
  [[ -n "$cidr" ]] && ufw allow from "$cidr" to any port 443 proto tcp comment 'Cloudflare HTTPS v6'
done <<< "$CF_V6"
ufw --force enable
ufw status verbose

# --- nginx site -------------------------------------------------------------
log "Installing nginx site"
install -m 644 "$DEPLOY_DIR/nginx-ipcrawl.conf" /etc/nginx/sites-available/ipcrawl
ln -sf /etc/nginx/sites-available/ipcrawl /etc/nginx/sites-enabled/ipcrawl
rm -f /etc/nginx/sites-enabled/default
mkdir -p /etc/ssl/cloudflare
if [[ ! -f /etc/ssl/cloudflare/ipcrawl-origin.pem ]]; then
  echo
  echo "  !! Cloudflare origin cert not found at /etc/ssl/cloudflare/ipcrawl-origin.{pem,key}"
  echo "     Generate one (CF dashboard > SSL/TLS > Origin Server), upload both files,"
  echo "     then run: nginx -t && systemctl reload nginx"
  echo "     nginx is NOT started yet because the TLS config would fail to load."
else
  nginx -t
  systemctl enable nginx
  systemctl restart nginx
fi

# --- systemd unit -----------------------------------------------------------
log "Installing systemd unit (service starts once the app is deployed)"
install -m 644 "$DEPLOY_DIR/ipcrawl.service" /etc/systemd/system/ipcrawl.service

# Nightly backup timer.
if [[ -f "$DEPLOY_DIR/ipcrawl-backup.service" && -f "$DEPLOY_DIR/ipcrawl-backup.timer" ]]; then
  install -m 644 "$DEPLOY_DIR/ipcrawl-backup.service" /etc/systemd/system/ipcrawl-backup.service
  install -m 644 "$DEPLOY_DIR/ipcrawl-backup.timer" /etc/systemd/system/ipcrawl-backup.timer
  install -m 755 "$DEPLOY_DIR/backup.sh" "$APP_ROOT/backup.sh"
  chown "$APP_USER:$APP_USER" "$APP_ROOT/backup.sh"
fi
systemctl daemon-reload
systemctl enable ipcrawl.service
if [[ -f /etc/systemd/system/ipcrawl-backup.timer ]]; then
  systemctl enable --now ipcrawl-backup.timer
fi

log "Provisioning done."
cat <<EOF

Next steps (see deploy/CUTOVER.md for the full runbook):
  1. Upload /srv/ipcrawl/env  (from deploy/env.example, fill in the secrets)
  2. Upload the Cloudflare origin cert to /etc/ssl/cloudflare/ipcrawl-origin.{pem,key}
     then: nginx -t && systemctl reload nginx
  3. From your laptop:  ./deploy/migrate-data.sh   (moves D1/R2/KV data over)
  4. From your laptop:  ./deploy/deploy.sh          (builds + ships the app, starts service)
EOF
